# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_added', models.DateTimeField()),
                ('genre', models.TextField()),
                ('actors', models.TextField()),
                ('watched', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
