# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170422_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_actors', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_genre', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='genre',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='actor',
            field=models.ManyToManyField(to='movies.Actor'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='genre',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
    ]
